### ISSUE TITLE
Crimson Text Regular with emph command

### ISSUE THREAD

**Issue by sebastianbarfort** [mclevey/cv#1]
Hi, 
what a great CV! 

I've tried to clone your repo, but when I run XeLateX `\emph{}` commands render as normal text, not italic. Would you mind explaining how you installed Crimson Text Regular? I can't seem to get it to work.

Best, Sebastian

**Comment by mclevey** [comment]
Thanks! I can't really take much credit for the design, which is by Kieran Healy. I'm not sure why your \emph{} commands aren't working. Try specifying "Crimson" instead of "Crimson Text Regular." I installed the TTF using Font Book in OS X.

**Comment by sebastianbarfort** [comment]
Got it to work now. I converted TTF to OTF before installing, and apparently that caused the error. Thanks.

**Comment by mclevey** [comment]
Great!
